/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.NHANSU;

import Annotation.LogMessage;
import DAO.AccountDAO;
import DAO.PositionDAO;
import DAO.RoleDAO;
import DAO.StaffDAO;
import GUI.NHANSU.gui_account.HashUtil;
import GUI.ViewMain;
import Model.Account;
import Model.Staff;
import java.time.LocalDate;
import java.time.Period;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eramisme
 */
public class gui_registaff extends javax.swing.JPanel {
    
    private ViewMain viewmain;
    private LogMessage logMessage;


    /**
     * Creates new form gui_registaff
     */
    public gui_registaff(ViewMain viewmain) {
        this.viewmain = viewmain;
        this.logMessage = logMessage;
        initComponents();
        setAccountNumberDefault();
        
        RoleDAO daorole = new RoleDAO();
        List <String> roleName = daorole.getRoleNames();       
        for (String role : roleName){
            combobox_Vaitro.addItem(role);
        }
        
        PositionDAO daoposition = new PositionDAO();
        List <String> positionName = daoposition.getPositionName();
        for (String position : positionName){
            combobox_Vitri.addItem(position);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_TT = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_HoTen = new javax.swing.JTextField();
        txt_CCCD = new javax.swing.JTextField();
        txt_DiaChi = new javax.swing.JTextField();
        combobox_GioiTinh = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_NgaySinh = new javax.swing.JTextField();
        txt_SDT = new javax.swing.JTextField();
        btn_LammoiTT = new javax.swing.JButton();
        combobox_Vaitro = new javax.swing.JComboBox<>();
        combobox_Vitri = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_Taikhoan = new javax.swing.JTextField();
        txt_Matkhau = new javax.swing.JTextField();
        btnDangKi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        Panel_TT.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("THÔNG TIN NHÂN VIÊN");

        jLabel2.setText("Họ tên");

        jLabel3.setText("CCCD");

        jLabel4.setText("Ngày sinh");

        jLabel5.setText("Giới tính");

        jLabel6.setText("Vị Trí");

        jLabel7.setText("Địa chỉ");

        combobox_GioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Nam", "Nữ" }));

        jLabel12.setText("Số điện thoại");

        jLabel13.setText("Email");

        jLabel15.setText("Vai trò");

        btn_LammoiTT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_LammoiTT.setText("Làm mới");
        btn_LammoiTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LammoiTTMouseClicked(evt);
            }
        });
        btn_LammoiTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LammoiTTActionPerformed(evt);
            }
        });

        combobox_Vaitro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        combobox_Vaitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_VaitroActionPerformed(evt);
            }
        });

        combobox_Vitri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        combobox_Vitri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_VitriActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("THÔNG TIN TÀI KHOẢN");

        jLabel11.setText("Số tài khoản");

        jLabel14.setText("Mật khẩu");

        btnDangKi.setText("Đăng kí");
        btnDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("ĐĂNG KÝ NHÂN VIÊN");

        javax.swing.GroupLayout Panel_TTLayout = new javax.swing.GroupLayout(Panel_TT);
        Panel_TT.setLayout(Panel_TTLayout);
        Panel_TTLayout.setHorizontalGroup(
            Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TTLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_TTLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Panel_TTLayout.createSequentialGroup()
                        .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Panel_TTLayout.createSequentialGroup()
                                .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addGroup(Panel_TTLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel2))
                                        .addGap(33, 33, 33)
                                        .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_HoTen)
                                            .addComponent(combobox_GioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(Panel_TTLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_Taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_Matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel_TTLayout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel6)))
                                    .addGroup(Panel_TTLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDangKi)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_CCCD)
                                        .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(combobox_Vitri, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel_TTLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(combobox_Vaitro, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_TTLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                        .addComponent(txt_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_TTLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(Panel_TTLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_LammoiTT)))
                        .addGap(24, 24, 24))))
        );
        Panel_TTLayout.setVerticalGroup(
            Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_TTLayout.createSequentialGroup()
                        .addComponent(btn_LammoiTT)
                        .addGap(9, 9, 9)
                        .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(combobox_Vitri, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(combobox_Vaitro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_TTLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_TTLayout.createSequentialGroup()
                                .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel7)))
                            .addGroup(Panel_TTLayout.createSequentialGroup()
                                .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(combobox_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_TTLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel9))
                    .addGroup(Panel_TTLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_Taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(Panel_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_Matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_TT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_TT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LammoiTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LammoiTTActionPerformed
        // TODO add your handling code here:
        resetThongTin();
        setAccountNumberDefault();
        txt_HoTen.requestFocus();
    }//GEN-LAST:event_btn_LammoiTTActionPerformed

    private void btn_LammoiTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LammoiTTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_LammoiTTMouseClicked

    private void combobox_VaitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_VaitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_VaitroActionPerformed

    private void combobox_VitriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_VitriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_VitriActionPerformed

    private void btnDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKiActionPerformed
        // TODO add your handling code here:
        String fullName = txt_HoTen.getText().trim();
        String ssn = txt_CCCD.getText().trim();
        String dobText = txt_NgaySinh.getText().trim();
        String genderText = combobox_GioiTinh.getSelectedItem().toString();
        String phone = txt_SDT.getText().trim();
        String address = txt_DiaChi.getText().trim();
        String email = txt_Email.getText().trim();
        String password = txt_Matkhau.getText().trim();
        String roleName = (String) combobox_Vaitro.getSelectedItem();
        String positionName = (String) combobox_Vitri.getSelectedItem();
        String accountNumberText = txt_Taikhoan.getText().trim();

        // Kiểm tra dữ liệu có trống hay không?
        if (fullName.isEmpty() || ssn.isEmpty() || phone.isEmpty() || email.isEmpty() ||
            password.isEmpty() || roleName == null || positionName == null || dobText.isEmpty() || accountNumberText.isEmpty()) {
            log_message("Vui lòng nhập đầy đủ thông tin");
            return;
        }

        // Kiểm tra CCCD
        if (!ssn.matches("^0\\d{11}$")) {
            log_message("CCCD phải đủ 12 số và bắt đầu là 0");
            return;
        }

        // Kiểm tra số điện thoại
        if (!phone.matches("^0\\d{9}$")) {
            log_message("SĐT phải đủ 10 số và bắt đầu là 0");
            return;
        }

        // Kiểm tra email
        if (!email.matches("^[\\w.+\\-]+@gmail\\.com$")) {
            log_message("Email phải đúng dạng @gmail.com");
            return;
        }

        // Kiểm tra ngày sinh
        LocalDate dob;
        try {
            dob = LocalDate.parse(dobText);
        } catch (Exception e) {
            log_message("Ngày sinh đúng dạng yyyy-MM-dd");
            return;
        }

        // Kiểm tra tuổi
        if (Period.between(dob, LocalDate.now()).getYears() < 18) {
            log_message("Phải đủ 18 tuổi trở lên");
            return;
        }

        // Kiểm tra số tài khoản
        int newAccountNumber;
        newAccountNumber = Integer.parseInt(accountNumberText);

        // Kiểm tra tính duy nhất của thông tin nhân viên
        if (StaffDAO.getInstance().isSsnExists(ssn, 0)) {
            log_message("CCCD đã tồn tại.");
            return;
        }
        if (StaffDAO.getInstance().isPhoneExists(phone, 0)) {
            log_message("Số điện thoại đã tồn tại.");
            return;
        }
        if (StaffDAO.getInstance().isEmailExists(email, 0)) {
            log_message("Email đã tồn tại.");
            return;
        }
        // Tạo tài khoản
        int roleId = RoleDAO.getInstance().getRoleIdByName(roleName);
        String hashedPassword = HashUtil.toSHA256(password);
        Account acc = new Account(newAccountNumber, hashedPassword, true, roleId); 
        boolean accCreated = AccountDAO.getInstance().insert(acc);

        if (!accCreated) {
            log_message("Tạo tài khoản thất bại");
            return;
        }

        // Tạo nhân viên
        int positionId = PositionDAO.getInstance().getPositionIdByName(positionName);
        String gender = genderText.equals("Nam") ? "M" : "F";
        Staff staff = new Staff(0, roleId, fullName, ssn, dob, gender, phone, address, email, true, positionId, newAccountNumber); // Trạng thái mặc định là Còn làm việc
        boolean staffCreated = StaffDAO.getInstance().insert(staff);

        if (staffCreated) {
            log_message("Đăng ký thành công");
            resetThongTin();
            setAccountNumberDefault();
        } else {
            log_message("Đăng ký thất bại");
            AccountDAO.getInstance().delete(newAccountNumber);
        }

    }//GEN-LAST:event_btnDangKiActionPerformed
   
    private void setAccountNumberDefault() {
        int acc = AccountDAO.getInstance().getMaxAccountNumber() + 1;
        txt_Taikhoan.setText(String.valueOf(acc));
        txt_Taikhoan.setEditable(false);
    }

    private void resetThongTin() {
        txt_HoTen.setText("");
        txt_CCCD.setText("");
        txt_NgaySinh.setText("");
        txt_SDT.setText("");
        txt_DiaChi.setText("");
        txt_Email.setText("");
        txt_Matkhau.setText("");
        combobox_GioiTinh.setSelectedIndex(0);
        combobox_Vitri.setSelectedIndex(0);
    }

    private void log_message(String message) {
        this.logMessage = new LogMessage(message) {
            @Override
            public void action() {
                this.setVisible(false);
                viewmain.setEnabled(true);
                viewmain.requestFocus();
            }
        };
        logMessage.setLocationRelativeTo(null);
        this.logMessage.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_TT;
    private javax.swing.JButton btnDangKi;
    private javax.swing.JButton btn_LammoiTT;
    private javax.swing.JComboBox<String> combobox_GioiTinh;
    private javax.swing.JComboBox<String> combobox_Vaitro;
    private javax.swing.JComboBox<String> combobox_Vitri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_CCCD;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_HoTen;
    private javax.swing.JTextField txt_Matkhau;
    private javax.swing.JTextField txt_NgaySinh;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_Taikhoan;
    // End of variables declaration//GEN-END:variables
}
